name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-22.04  # Используем Ubuntu 22.04 вместо 24.04
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: wellness
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:6
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.23
    
    - name: Test
      run: |
        go test -v ./...
    
  build-and-test:
    needs: test
    runs-on: ubuntu-22.04  # Используем Ubuntu 22.04 вместо 24.04
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker
      uses: docker/setup-qemu-action@v2
      uses: docker/setup-buildx-action@v2
    
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose-plugin
        docker compose version
    
    - name: Build and test
      run: |
        docker compose -f docker-compose.yml up -d --build
        sleep 15
        curl --fail http://localhost:8080/api/v1/health || (docker compose logs && exit 1)
    
    - name: Show logs if failed
      if: failure()
      run: |
        docker compose logs