name: Wellness Center CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit-tests:
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: wellness
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      prometheus:
        image: prom/prometheus
        ports:
          - 9090:9090
        volumes:
          - ./config/prometheus-test.yml:/etc/prometheus/prometheus.yml
        options: >-
          --health-cmd "wget -qO- http://localhost:9090/-/ready || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.23
    
    - name: Run tests
      run: |
        go test -v ./...

  integration-tests:
    needs: unit-tests
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
    
    - name: Start services
      run: |
        docker network create wellness-net
        
        # Основные сервисы
        docker run -d --name redis --network wellness-net -p 6379:6379 redis:6
        docker run -d --name postgres \
          --network wellness-net \
          -e POSTGRES_USER=postgres \
          -e POSTGRES_PASSWORD=postgres \
          -e POSTGRES_DB=wellness \
          -p 5432:5432 \
          postgres:13
        
        # Prometheus
        docker run -d --name prometheus \
          --network wellness-net \
          -p 9090:9090 \
          -v $PWD/config/prometheus-test.yml:/etc/prometheus/prometheus.yml \
          prom/prometheus
        
        sleep 10
    
    - name: Build and test
      run: |
        docker build -t wellness-app .
        docker run -d --name app \
          --network wellness-net \
          -p 8080:8080 \
          -e PROMETHEUS_ENABLED=true \
          wellness-app
        sleep 5
        curl --fail http://localhost:8080/api/v1/health
        curl --fail http://localhost:8080/metrics
    
    - name: Cleanup
      if: always()
      run: |
        docker stop app redis postgres prometheus || true
        docker rm app redis postgres prometheus || true
        docker network rm wellness-net || true